default: &default
  secret_key_base: <%= SecureRandom.hex(30) %>
  flickr_api_key: <%= ENV["FLICKR_API_KEY"] %>
  flickr_shared_secret: <%= ENV["FLICKR_SHARED_SECRET"] %>
  _500px_consumer_key: <%= ENV["500PX_CONSUMER_KEY"] %>
  _500px_consumer_secret: <%= ENV["500PX_CONSUMER_SECRET"] %>
  _500px_username: <%= ENV["500PX_USERNAME"] %>
  _500px_password: <%= ENV["500PX_PASSWORD"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>